version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.4.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  backend:
    build: 
      dockerfile: ./compose/backend/Dockerfile
      context: .
    command: bash -c "alembic upgrade head && uvicorn --port 8000 --host 0.0.0.0 app.main:app"
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
      - elasticsearch

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  frontend:
    build: 
      dockerfile: ./compose/frontend/Dockerfile
      context: .
    image: frontend
    restart: unless-stopped

  nginx:
    build: 
      dockerfile: ./compose/nginx/Dockerfile
      context: .
    image: nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
    volumes:
      - ./mounts/uwsgi:/uwsgi
      - ./mounts/logs/nginx:/var/log/nginx
      - ./mounts/media:/webapp/media:ro
      - ./mounts/static:/webapp/static:ro
